#!/usr/bin/env bash
#diaplays Best School 10 times

num=0
while [ $num -lt 10 ]
do
	if [ $num = 3 ]
	then
		echo "bad luck"
	elif [ $num = 7 ]
	then
		echo "good luck"
	else
	echo "Best School"
	fi
	((num=num+1))
	
done
